/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminDashboardRouteImport } from './routes/superadmin.dashboard'
import { Route as AppHomeRouteImport } from './routes/app.home'
import { Route as AppAdminRouteImport } from './routes/app.admin'
import { Route as AppIndicationIdRouteImport } from './routes/app.indication.$id'
import { Route as AppIndicationIdTimelinesRouteImport } from './routes/app.indication.$id.timelines'
import { Route as AppIndicationIdSocialRouteImport } from './routes/app.indication.$id.social'
import { Route as AppIndicationIdReportsRouteImport } from './routes/app.indication.$id.reports'
import { Route as AppIndicationIdPublicationsRouteImport } from './routes/app.indication.$id.publications'
import { Route as AppIndicationIdProductProfilesRouteImport } from './routes/app.indication.$id.product-profiles'
import { Route as AppIndicationIdNewsRouteImport } from './routes/app.indication.$id.news'
import { Route as AppIndicationIdCompetitorsRouteImport } from './routes/app.indication.$id.competitors'
import { Route as AppIndicationIdCompetitiveLandscapeRouteImport } from './routes/app.indication.$id.competitive-landscape'
import { Route as AppIndicationIdClinicalTrialsRouteImport } from './routes/app.indication.$id.clinical-trials'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminDashboardRoute = SuperadminDashboardRouteImport.update({
  id: '/superadmin/dashboard',
  path: '/superadmin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicationIdRoute = AppIndicationIdRouteImport.update({
  id: '/indication/$id',
  path: '/indication/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicationIdTimelinesRoute =
  AppIndicationIdTimelinesRouteImport.update({
    id: '/timelines',
    path: '/timelines',
    getParentRoute: () => AppIndicationIdRoute,
  } as any)
const AppIndicationIdSocialRoute = AppIndicationIdSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => AppIndicationIdRoute,
} as any)
const AppIndicationIdReportsRoute = AppIndicationIdReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppIndicationIdRoute,
} as any)
const AppIndicationIdPublicationsRoute =
  AppIndicationIdPublicationsRouteImport.update({
    id: '/publications',
    path: '/publications',
    getParentRoute: () => AppIndicationIdRoute,
  } as any)
const AppIndicationIdProductProfilesRoute =
  AppIndicationIdProductProfilesRouteImport.update({
    id: '/product-profiles',
    path: '/product-profiles',
    getParentRoute: () => AppIndicationIdRoute,
  } as any)
const AppIndicationIdNewsRoute = AppIndicationIdNewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => AppIndicationIdRoute,
} as any)
const AppIndicationIdCompetitorsRoute =
  AppIndicationIdCompetitorsRouteImport.update({
    id: '/competitors',
    path: '/competitors',
    getParentRoute: () => AppIndicationIdRoute,
  } as any)
const AppIndicationIdCompetitiveLandscapeRoute =
  AppIndicationIdCompetitiveLandscapeRouteImport.update({
    id: '/competitive-landscape',
    path: '/competitive-landscape',
    getParentRoute: () => AppIndicationIdRoute,
  } as any)
const AppIndicationIdClinicalTrialsRoute =
  AppIndicationIdClinicalTrialsRouteImport.update({
    id: '/clinical-trials',
    path: '/clinical-trials',
    getParentRoute: () => AppIndicationIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/home': typeof AppHomeRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/app/indication/$id': typeof AppIndicationIdRouteWithChildren
  '/app/indication/$id/clinical-trials': typeof AppIndicationIdClinicalTrialsRoute
  '/app/indication/$id/competitive-landscape': typeof AppIndicationIdCompetitiveLandscapeRoute
  '/app/indication/$id/competitors': typeof AppIndicationIdCompetitorsRoute
  '/app/indication/$id/news': typeof AppIndicationIdNewsRoute
  '/app/indication/$id/product-profiles': typeof AppIndicationIdProductProfilesRoute
  '/app/indication/$id/publications': typeof AppIndicationIdPublicationsRoute
  '/app/indication/$id/reports': typeof AppIndicationIdReportsRoute
  '/app/indication/$id/social': typeof AppIndicationIdSocialRoute
  '/app/indication/$id/timelines': typeof AppIndicationIdTimelinesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/home': typeof AppHomeRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/app/indication/$id': typeof AppIndicationIdRouteWithChildren
  '/app/indication/$id/clinical-trials': typeof AppIndicationIdClinicalTrialsRoute
  '/app/indication/$id/competitive-landscape': typeof AppIndicationIdCompetitiveLandscapeRoute
  '/app/indication/$id/competitors': typeof AppIndicationIdCompetitorsRoute
  '/app/indication/$id/news': typeof AppIndicationIdNewsRoute
  '/app/indication/$id/product-profiles': typeof AppIndicationIdProductProfilesRoute
  '/app/indication/$id/publications': typeof AppIndicationIdPublicationsRoute
  '/app/indication/$id/reports': typeof AppIndicationIdReportsRoute
  '/app/indication/$id/social': typeof AppIndicationIdSocialRoute
  '/app/indication/$id/timelines': typeof AppIndicationIdTimelinesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/admin': typeof AppAdminRoute
  '/app/home': typeof AppHomeRoute
  '/superadmin/dashboard': typeof SuperadminDashboardRoute
  '/app/indication/$id': typeof AppIndicationIdRouteWithChildren
  '/app/indication/$id/clinical-trials': typeof AppIndicationIdClinicalTrialsRoute
  '/app/indication/$id/competitive-landscape': typeof AppIndicationIdCompetitiveLandscapeRoute
  '/app/indication/$id/competitors': typeof AppIndicationIdCompetitorsRoute
  '/app/indication/$id/news': typeof AppIndicationIdNewsRoute
  '/app/indication/$id/product-profiles': typeof AppIndicationIdProductProfilesRoute
  '/app/indication/$id/publications': typeof AppIndicationIdPublicationsRoute
  '/app/indication/$id/reports': typeof AppIndicationIdReportsRoute
  '/app/indication/$id/social': typeof AppIndicationIdSocialRoute
  '/app/indication/$id/timelines': typeof AppIndicationIdTimelinesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/home'
    | '/superadmin/dashboard'
    | '/app/indication/$id'
    | '/app/indication/$id/clinical-trials'
    | '/app/indication/$id/competitive-landscape'
    | '/app/indication/$id/competitors'
    | '/app/indication/$id/news'
    | '/app/indication/$id/product-profiles'
    | '/app/indication/$id/publications'
    | '/app/indication/$id/reports'
    | '/app/indication/$id/social'
    | '/app/indication/$id/timelines'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/home'
    | '/superadmin/dashboard'
    | '/app/indication/$id'
    | '/app/indication/$id/clinical-trials'
    | '/app/indication/$id/competitive-landscape'
    | '/app/indication/$id/competitors'
    | '/app/indication/$id/news'
    | '/app/indication/$id/product-profiles'
    | '/app/indication/$id/publications'
    | '/app/indication/$id/reports'
    | '/app/indication/$id/social'
    | '/app/indication/$id/timelines'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/admin'
    | '/app/home'
    | '/superadmin/dashboard'
    | '/app/indication/$id'
    | '/app/indication/$id/clinical-trials'
    | '/app/indication/$id/competitive-landscape'
    | '/app/indication/$id/competitors'
    | '/app/indication/$id/news'
    | '/app/indication/$id/product-profiles'
    | '/app/indication/$id/publications'
    | '/app/indication/$id/reports'
    | '/app/indication/$id/social'
    | '/app/indication/$id/timelines'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SuperadminDashboardRoute: typeof SuperadminDashboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/dashboard': {
      id: '/superadmin/dashboard'
      path: '/superadmin/dashboard'
      fullPath: '/superadmin/dashboard'
      preLoaderRoute: typeof SuperadminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/admin': {
      id: '/app/admin'
      path: '/admin'
      fullPath: '/app/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indication/$id': {
      id: '/app/indication/$id'
      path: '/indication/$id'
      fullPath: '/app/indication/$id'
      preLoaderRoute: typeof AppIndicationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/indication/$id/timelines': {
      id: '/app/indication/$id/timelines'
      path: '/timelines'
      fullPath: '/app/indication/$id/timelines'
      preLoaderRoute: typeof AppIndicationIdTimelinesRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/social': {
      id: '/app/indication/$id/social'
      path: '/social'
      fullPath: '/app/indication/$id/social'
      preLoaderRoute: typeof AppIndicationIdSocialRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/reports': {
      id: '/app/indication/$id/reports'
      path: '/reports'
      fullPath: '/app/indication/$id/reports'
      preLoaderRoute: typeof AppIndicationIdReportsRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/publications': {
      id: '/app/indication/$id/publications'
      path: '/publications'
      fullPath: '/app/indication/$id/publications'
      preLoaderRoute: typeof AppIndicationIdPublicationsRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/product-profiles': {
      id: '/app/indication/$id/product-profiles'
      path: '/product-profiles'
      fullPath: '/app/indication/$id/product-profiles'
      preLoaderRoute: typeof AppIndicationIdProductProfilesRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/news': {
      id: '/app/indication/$id/news'
      path: '/news'
      fullPath: '/app/indication/$id/news'
      preLoaderRoute: typeof AppIndicationIdNewsRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/competitors': {
      id: '/app/indication/$id/competitors'
      path: '/competitors'
      fullPath: '/app/indication/$id/competitors'
      preLoaderRoute: typeof AppIndicationIdCompetitorsRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/competitive-landscape': {
      id: '/app/indication/$id/competitive-landscape'
      path: '/competitive-landscape'
      fullPath: '/app/indication/$id/competitive-landscape'
      preLoaderRoute: typeof AppIndicationIdCompetitiveLandscapeRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
    '/app/indication/$id/clinical-trials': {
      id: '/app/indication/$id/clinical-trials'
      path: '/clinical-trials'
      fullPath: '/app/indication/$id/clinical-trials'
      preLoaderRoute: typeof AppIndicationIdClinicalTrialsRouteImport
      parentRoute: typeof AppIndicationIdRoute
    }
  }
}

interface AppIndicationIdRouteChildren {
  AppIndicationIdClinicalTrialsRoute: typeof AppIndicationIdClinicalTrialsRoute
  AppIndicationIdCompetitiveLandscapeRoute: typeof AppIndicationIdCompetitiveLandscapeRoute
  AppIndicationIdCompetitorsRoute: typeof AppIndicationIdCompetitorsRoute
  AppIndicationIdNewsRoute: typeof AppIndicationIdNewsRoute
  AppIndicationIdProductProfilesRoute: typeof AppIndicationIdProductProfilesRoute
  AppIndicationIdPublicationsRoute: typeof AppIndicationIdPublicationsRoute
  AppIndicationIdReportsRoute: typeof AppIndicationIdReportsRoute
  AppIndicationIdSocialRoute: typeof AppIndicationIdSocialRoute
  AppIndicationIdTimelinesRoute: typeof AppIndicationIdTimelinesRoute
}

const AppIndicationIdRouteChildren: AppIndicationIdRouteChildren = {
  AppIndicationIdClinicalTrialsRoute: AppIndicationIdClinicalTrialsRoute,
  AppIndicationIdCompetitiveLandscapeRoute:
    AppIndicationIdCompetitiveLandscapeRoute,
  AppIndicationIdCompetitorsRoute: AppIndicationIdCompetitorsRoute,
  AppIndicationIdNewsRoute: AppIndicationIdNewsRoute,
  AppIndicationIdProductProfilesRoute: AppIndicationIdProductProfilesRoute,
  AppIndicationIdPublicationsRoute: AppIndicationIdPublicationsRoute,
  AppIndicationIdReportsRoute: AppIndicationIdReportsRoute,
  AppIndicationIdSocialRoute: AppIndicationIdSocialRoute,
  AppIndicationIdTimelinesRoute: AppIndicationIdTimelinesRoute,
}

const AppIndicationIdRouteWithChildren = AppIndicationIdRoute._addFileChildren(
  AppIndicationIdRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIndicationIdRoute: typeof AppIndicationIdRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppHomeRoute: AppHomeRoute,
  AppIndicationIdRoute: AppIndicationIdRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SuperadminDashboardRoute: SuperadminDashboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
